[tool.poetry]
name = "my-hypermodern-python"
version = "0.1.0"
description = "CLI application using python tooling as per the Hypermodern Python article series."
authors = ["Alex Grant <agrant@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Delacoal/my-hypermodern-python"
repository = "https://github.com/Delacoal/"
keywords = ["python, tooling"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"
click = "^8.1.2"
black = "^22.3.0"
isort = "^5.10.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
coverage = "^6.3.2"
pytest-mock = "^3.7.0"
flake8 = "^4.0.1"
black = "^22.3.0"
flake8-bandit = "^3.0.0"
flake8-black = "^0.3.3"
flake8-bugbear = "^22.4.25"
flake8-import-order = "^0.18.1"
safety = "^1.10.3"
mypy = "^0.961"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
my-hypermodern-python = "my_hypermodern_python.console:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["my_hypermodern_python"]

[tool.coverage.report]
show_missing = true
fail_under = 100